language: ruby
rvm:
    - 1.9.3
        gemfile: Gemfile
    - 2.0.0
        gemfile: Gemfile
    - 2.1.0
        gemfile: Gemfile
    - jruby-19mode
        gemfile: Gemfile.jruby
before_install: 
    - gem update --system
    - gem --version
    - gem install bundler
    - bundler --version
